// react-client/src/ui/register/Register.jsx
import { Link } from 'react-router-dom'
import './register.css'
import { useRef } from 'react'
import { register } from '../../http/auth'
import { useMutation } from 'react-query'
import { useNavigate } from 'react-router-dom'
import { storeAuth } from '../../storage/auth'

function Register() {

    const navigate = useNavigate()

    const mutation = useMutation(user => register(user), {
        onSuccess: (response) => {
            storeAuth(response.data.user)
            navigate('/')
        }
    })

    const usernameInput = useRef()
    const passwordInput = useRef()
    const nameInput = useRef()
    const groupInput = useRef()

    const submit = (event) => {
        event.preventDefault()
        const user = {
            username: usernameInput.current.value,
            password: passwordInput.current.value,
            name: nameInput.current.value,
            group: groupInput.current.value,
        }

        mutation.mutate(user)
    }

    return (
        <main className='center'>
            <form>
                <h1> Verse </h1>
                { mutation.isError ? 
                    <span className="error"> {mutation.error.response.data.message} </span> 
                    :
                     null
                }
                <input ref={usernameInput} type="text" placeholder="Username" />
                <input ref={passwordInput} type="text" placeholder="Password" />

                <input ref={nameInput} type="text" placeholder="Name" />
                <input ref={groupInput} type="text" placeholder="Group" />

                <button onClick={submit} disabled={mutation.isLoading}> {mutation.isLoading ? 'Loading' : 'Register'} </button>

                <Link to="/login"> Already have account? Login </Link>
            </form>
        </main>
    )
}

export default Register

// client/src/pages/Register.svelte
<script lang="ts">
    import { Link } from 'svelte-navigator'

    import { httpRegister } from "../http/auth.http";
    import { setAuth } from "../stores/auth.store";

    import { navigate } from 'svelte-navigator'


    let usernameInput: HTMLInputElement
    let passwordInput: HTMLInputElement
    let nameInput: HTMLInputElement
    let groupInput: HTMLInputElement

    let isLoading: boolean = false
    let error: string | null = null

    function login(event: any) {

        isLoading = true

        httpRegister(
            usernameInput.value,
            passwordInput.value,
            nameInput.value,
            groupInput.value
        ).subscribe(response => {
            isLoading = false
            error = response.status == 'error' ? response.message : null
            setAuth(response.data)
            navigate('/')
        })
    }

</script>

<main>

    <form on:submit|preventDefault={login}>
        <h1> Verse </h1>
        {#if error}
            <span class="error"> {error} </span>
        {/if}
        <input bind:this={usernameInput} type="text" placeholder="Username">
        <input bind:this={passwordInput} type="text" placeholder="Password">

        <input bind:this={nameInput} type="text" placeholder="Name">
        <input bind:this={groupInput} type="text" placeholder="Group">

        <button disabled={isLoading}> Register </button>

        <Link to="/login"> Already have account? Login </Link>
    </form>

</main>

<style>
    main {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    form {
        display: flex;
        flex-direction: column;
        gap: 10px;

    }
</style>
